// Import all 3 solutions
const solution1 = require("./solutions/solution1"); // Brute Force
const solution2 = require("./solutions/solution2"); // Backtracking
const solution3 = require("./solutions/solution3"); // BFS

// Store solutions
const solutions = [
  { name: "Brute Force", fn: solution1 },
  { name: "Backtracking", fn: solution2 },
  { name: "BFS Queue", fn: solution3 },
];

// Store test cases
const testCases = [
  { digits: "2", expected: ["a", "b", "c"] },
  { digits: "3", expected: ["d", "e", "f"] },
  { digits: "4", expected: ["g", "h", "i"] },
  { digits: "5", expected: ["j", "k", "l"] },
  { digits: "6", expected: ["m", "n", "o"] },

  { digits: "7", expected: ["p", "q", "r", "s"] },
  { digits: "8", expected: ["t", "u", "v"] },
  { digits: "9", expected: ["w", "x", "y", "z"] },

  {
    digits: "23",
    expected: ["ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf"],
  },
  {
    digits: "32",
    expected: ["da", "db", "dc", "ea", "eb", "ec", "fa", "fb", "fc"],
  },

  {
    digits: "22",
    expected: ["aa", "ab", "ac", "ba", "bb", "bc", "ca", "cb", "cc"],
  },
  {
    digits: "79",
    expected: [
      "pw",
      "px",
      "py",
      "pz",
      "qw",
      "qx",
      "qy",
      "qz",
      "rw",
      "rx",
      "ry",
      "rz",
      "sw",
      "sx",
      "sy",
      "sz",
    ],
  },

  {
    digits: "234",
    expected: [
      "adg",
      "adh",
      "adi",
      "aeg",
      "aeh",
      "aei",
      "afg",
      "afh",
      "afi",
      "bdg",
      "bdh",
      "bdi",
      "beg",
      "beh",
      "bei",
      "bfg",
      "bfh",
      "bfi",
      "cdg",
      "cdh",
      "cdi",
      "ceg",
      "ceh",
      "cei",
      "cfg",
      "cfh",
      "cfi",
    ],
  },

  {
    digits: "222",
    expected: [
      "aaa",
      "aab",
      "aac",
      "aba",
      "abb",
      "abc",
      "aca",
      "acb",
      "acc",
      "baa",
      "bab",
      "bac",
      "bba",
      "bbb",
      "bbc",
      "bca",
      "bcb",
      "bcc",
      "caa",
      "cab",
      "cac",
      "cba",
      "cbb",
      "cbc",
      "cca",
      "ccb",
      "ccc",
    ],
  },

  {
    digits: "99",
    expected: [
      "ww",
      "wx",
      "wy",
      "wz",
      "xw",
      "xx",
      "xy",
      "xz",
      "yw",
      "yx",
      "yy",
      "yz",
      "zw",
      "zx",
      "zy",
      "zz",
    ],
  },

  {
    digits: "27",
    expected: [
      "ap",
      "aq",
      "ar",
      "as",
      "bp",
      "bq",
      "br",
      "bs",
      "cp",
      "cq",
      "cr",
      "cs",
    ],
  },

  {
    digits: "56",
    expected: ["jm", "jn", "jo", "km", "kn", "ko", "lm", "ln", "lo"],
  },

  {
    digits: "89",
    expected: [
      "tw",
      "tx",
      "ty",
      "tz",
      "uw",
      "ux",
      "uy",
      "uz",
      "vw",
      "vx",
      "vy",
      "vz",
    ],
  },

  {
    digits: "2345",
    expected: [
      "adgj",
      "adgk",
      "adgl",
      "adhj",
      "adhk",
      "adhl",
      "adij",
      "adik",
      "adil",
      "aegj",
      "aegk",
      "aegl",
      "aehj",
      "aehk",
      "aehl",
      "aeij",
      "aeik",
      "aeil",
      "afgj",
      "afgk",
      "afgl",
      "afhj",
      "afhk",
      "afhl",
      "afij",
      "afik",
      "afil",
      "bdgj",
      "bdgk",
      "bdgl",
      "bdhj",
      "bdhk",
      "bdhl",
      "bdij",
      "bdik",
      "bdil",
      "begj",
      "begk",
      "begl",
      "behj",
      "behk",
      "behl",
      "beij",
      "beik",
      "beil",
      "bfgj",
      "bfgk",
      "bfgl",
      "bfhj",
      "bfhk",
      "bfhl",
      "bfij",
      "bfik",
      "bfil",
      "cdgj",
      "cdgk",
      "cdgl",
      "cdhj",
      "cdhk",
      "cdhl",
      "cdij",
      "cdik",
      "cdil",
      "cegj",
      "cegk",
      "cegl",
      "cehj",
      "cehk",
      "cehl",
      "ceij",
      "ceik",
      "ceil",
      "cfgj",
      "cfgk",
      "cfgl",
      "cfhj",
      "cfhk",
      "cfhl",
      "cfij",
      "cfik",
      "cfil",
    ],
  },

  {
    digits: "777",
    expected: [
      "ppp",
      "ppq",
      "ppr",
      "pps",
      "pqp",
      "pqq",
      "pqr",
      "pqs",
      "prp",
      "prq",
      "prr",
      "prs",
      "psp",
      "psq",
      "psr",
      "pss",
      "qpp",
      "qpq",
      "qpr",
      "qps",
      "qqp",
      "qqq",
      "qqr",
      "qqs",
      "qrp",
      "qrq",
      "qrr",
      "qrs",
      "qsp",
      "qsq",
      "qsr",
      "qss",
      "rpp",
      "rpq",
      "rpr",
      "rps",
      "rqp",
      "rqq",
      "rqr",
      "rqs",
      "rrp",
      "rrq",
      "rrr",
      "rrs",
      "rsp",
      "rsq",
      "rsr",
      "rss",
      "spp",
      "spq",
      "spr",
      "sps",
      "sqp",
      "sqq",
      "sqr",
      "sqs",
      "srp",
      "srq",
      "srr",
      "srs",
      "ssp",
      "ssq",
      "ssr",
      "sss",
    ],
  },

  // Edge-like valid constraints
  { digits: "2222", expectedLength: 81 },
  { digits: "9999", expectedLength: 256 },
  { digits: "2349", expectedLength: 108 },
  { digits: "5687", expectedLength: 108 },

  { digits: "23", expectedLength: 9 },
  { digits: "234", expectedLength: 27 },
  { digits: "79", expectedLength: 16 },
  { digits: "567", expectedLength: 36 },
  { digits: "89", expectedLength: 12 },
  { digits: "2348", expectedLength: 81 },
];

// Run tests
describe("Letter Combinations - All Implementations", () => {
  solutions.forEach(({ name, fn }) => {
    describe(name, () => {
      testCases.forEach(({ digits, expected, expectedLength }, index) => {
        test(`Test Case ${index + 1}`, () => {
          const result = fn(digits);

          if (expected) {
            expect(result.length).toBe(expected.length);
            expect([...result].sort()).toEqual([...expected].sort());
          } else if (expectedLength) {
            expect(result.length).toBe(expectedLength);
          } else {
            expect(result).toEqual([]);
          }
        });
      });
    });
  });
});
